import type { Metadata } from "next";
import '@/views/style/global.scss'
import { ProviderWrapper } from "@/shared/wrappers/ProviderWrapper";
import { Basket } from "@/widgets/basket/Basket";
import { Header } from "@/widgets/header/Header";
import { Footer } from "@/widgets/footer/Footer";
import { InitWrapper } from "@/shared/wrappers/InitWrapper";
import { OnlineSupport } from "@/features/online-support/OnlineSupport";
import { MobileMenu } from "@/widgets/mobile-menu/MobileMenu";

// if add next js font 
// import { Inter } from "next/font/google";
// const inter = Inter({ subsets: ["latin"] });
// <body className={inter.className}>{children}</body>

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="bg-main-bg text-main">
        <ProviderWrapper>
          <InitWrapper>
            <Header />
            <Basket />
            <div className="">
              {children}
            </div>
            <Footer />
            <OnlineSupport hiddenPage="product"/>
            <MobileMenu />
          </InitWrapper>
        </ProviderWrapper>
      </body>
    </html>
  );
}
