import type { Metadata } from "next";
import '@/views/style/global.scss'
import { ProviderWrapper } from "@/shared/wrappers/ProviderWrapper";
import { Basket } from "@/widgets/basket/Basket";
import { Header } from "@/widgets/header/Header";
import { Footer } from "@/widgets/footer/Footer";
import { InitWrapper } from "@/shared/wrappers/InitWrapper";
import { ChatWidget } from "@/widgets/chat-widget/ChatWidget";
import { OnlineSupport } from "@/features/online-support/OnlineSupport";

// if add next js font 
// import { Inter } from "next/font/google";
// const inter = Inter({ subsets: ["latin"] });
// <body className={inter.className}>{children}</body>

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <ProviderWrapper>
        <InitWrapper>
          <body className="bg-main-bg text-main">
            <Header />
            <Basket />
            <div className="">
              {children}
            </div>
            <Footer />
            <OnlineSupport />
          </body>
        </InitWrapper>
      </ProviderWrapper>
    </html>
  );
}
